### PR TITLE
[feature/random_game] RandomGame 구현

### PR DESCRIPTION
**Pull request by l2hyunwoo**
## Issue

랜덤게임 구현했읍니다!

### CODE REVIEW

**Review by sudosubin — APPROVED** [review]
looks good to me :+1:

**Comment by Blue-Hope** [comment]
lgtm

**Review by Blue-Hope — APPROVED** [review]

**Review by davin111 — APPROVED** [review]
LGTM

**Comment by l2hyunwoo** [comment]
과반의 동의로 Merge!

**Pull request merged**
